from app.api.v1.defect_type import router as defect_type_router
from app.api.v1.photo import router as photo_router
from app.api.v1.role import router as role_router
from app.api.v1.sector import router as sector_router
from app.api.v1.survey import router as survey_router
from app.api.v1.survey_defect import router as survey_defect_router
from app.api.v1.team import router as team_router
from app.api.v1.tree import router as tree_router
from app.api.v1.user import router as user_router
